### ISSUE TITLE
imtoken saya tidak bisa ngirim

### ISSUE THREAD

**Issue by 4muhamadilyas** [Didericis/twitter-rumor-spreader#1] opened 2020-06-18 06:00 UTC

**Comment by 4muhamadilyas** [comment] 2020-06-18 06:01
imtoken saya tidak bisa ngirim

**Comment by marleyjustin08** [comment] 2020-10-11 14:57
>   #@[https://github.com/Diderici
Duplicate of #s/twitter-rumor-spreader/issues/1#issue-640933096](https://github.com/Didericis/twitter-rumor-spreader/issues/1#issue-640933096)

**Comment by marleyjustin08** [comment] 2020-10-12 07:36
#
Duplicate of #

**Comment by Didericis** [comment] 2020-10-12 17:35
@marleyjustin08 I don't understand what the issue is here.

**Closed as completed** 2020-11-28 06:14 UTC
